const arrayOfUsers = [
    // Admin
    {
        username: "Xiwan",
        name: "Liza",
        lastname: "Saravia",
        profilepic: "https://i.imgur.com/LBFq1of.png",
        email: "lizasaravia@gmail.com",
        password: "1234aA",
        birth: 12121976,
        type: "admin",
        state: "approved",
    },
    // Artistas
    {
        username: "Guimtio",
        name: "Guim",
        lastname: "Zarraluki",
        profilepic: "https://i.imgur.com/0VsGfXY.jpg",
        email: "guimtio@gmail.com",
        password: "SSKsods#!djjd323",
        birth: 10121970,
        type: "artist",
        state: "approved",
    },
    {
        username: "PaulinaPeterArt",
        name: "Paulina",
        lastname: "Peter",
        profilepic: "https://i.imgur.com/Fg4GOOt.jpg",
        email: "paulinapeter@gmail.com",
        password: "Sjdj$$$//djdj7",
        birth: 21021999,
        type: "artist",
        state: "approved",
    },
    {
        username: "Jajko",
        name: "Jej",
        lastname: "Jajkowatosc",
        profilepic: "https://i.imgur.com/lfgV1kK.jpg",
        email: "jajko@gmail.com",
        password: "Gsksek#$%jd7jd#m%4",
        birth: 12121976,
        type: "artist",
        state: "approved",
    },
    {
        username: "Kiwano",
        name: "Vincent",
        lastname: "Cassel",
        profilepic: "https://i.imgur.com/JPw2CNP.jpg",
        email: "vincentcassel8@gmail.com",
        password: "alsdlasd&%ma2332M",
        birth: 17011978,
        type: "artist",
        state: "approved",
    },
    {
        username: "RaymondLemstra",
        name: "Raymond",
        lastname: "Lemstra",
        profilepic: "https://i.imgur.com/6HSrNEA.jpg",
        email: "raymondlemstra@gmail.com",
        password: "KlK738j%$%/(dasd",
        birth: 02072001,
        type: "artist",
        state: "approved",
    },
    {
        username: "AgustinaRuizArte",
        name: "Agustina",
        lastname: "Ruiz",
        profilepic: "https://i.imgur.com/Qd3Xmdz.jpg",
        email: "mansdfsdfu44@gmail.com",
        password: "KlK738j%$%/(dasd",
        birth: 26061993,
        type: "artist",
        state: "approved",
    },
    // Compradores
    {
        username: "agus",
        name: "Agustina",
        lastname: "Coronado",
        profilepic: "https://i.imgur.com/LBFq1of.png",
        email: "agus@gmail.com",
        password: "1234aA",
        birth: 12121976,
        type: "admin",
        state: "approved",
    },
    {
        username: "flor",
        name: "Florencia",
        lastname: "Almada",
        profilepic: "https://i.imgur.com/LBFq1of.png",
        email: "flor@gmail.com",
        password: "SSKsods#!djjd323",
        birth: 10121970,
        type: "user",
        state: "approved",
    },
    {
        username: "santil",
        name: "Santiago",
        lastname: "Longueira",
        profilepic: "https://i.imgur.com/LBFq1of.png",
        email: "santil@gmail.com",
        password: "Sjdj$$$//djdj7",
        birth: 21021999,
        type: "user",
        state: "approved",
    },
    {
        username: "liza",
        name: "Liza",
        lastname: "Saravia",
        profilepic: "https://i.imgur.com/9sFP4Zr.jpg",
        email: "liza@gmail.com",
        password: "Gsksek#$%jd7jd#m%4",
        birth: 12121976,
        type: "artist",
        state: "approved",
    },
    {
        username: "santim",
        name: "Santi",
        lastname: "Molina",
        profilepic: "https://i.imgur.com/LBFq1of.png",
        email: "santim@gmail.com",
        password: "alsdlasd&%ma2332M",
        birth: 17011978,
        type: "user",
        state: "approved",
    },
    {
        username: "aylen",
        name: "Aylen",
        lastname: "Alderete",
        profilepic: "https://i.imgur.com/LBFq1of.png",
        email: "aylen@gmail.com",
        password: "KlK738j%$%/(dasd",
        birth: 02072001,
        type: "user",
        state: "approved",
    },
    {
        username: "andres",
        name: "Andres",
        lastname: "Gomez",
        profilepic: "https://i.imgur.com/LBFq1of.png",
        email: "andres@gmail.com",
        password: "KlK738j%$%/(dasd",
        birth: 26061993,
        type: "user",
        state: "approved",
    },
    {
        username: "matias",
        name: "Matias",
        lastname: "Cheverri",
        profilepic: "https://i.imgur.com/LBFq1of.png",
        email: "matias@gmail.com",
        password: "KlK738j%$%/(dasd",
        birth: 26061993,
        type: "user",
        state: "approved",
    },
    {
        username: "jorge",
        name: "Jorge",
        lastname: "Macias",
        profilepic: "https://i.imgur.com/LBFq1of.png",
        email: "jmaciasvesga@gmail.com",
        password: "KlK738j%$%/(dasd",
        birth: 26061993,
        type: "user",
        state: "approved",
    },
    {
        username: "comprador",
        name: "Com",
        lastname: "Prador",
        profilepic: "https://i.imgur.com/LBFq1of.png",
        email: "comprador@gmail.com",
        password:
            "$2a$10$kui1uaMdN0Ak2adaLBGkROoiCI6mcRKdbnEkpWFr1/5uBQw4fDRX.",
        birth: 21021999,
        type: "user",
        state: "approved",
    },
    {
        username: "artista",
        name: "Ar",
        lastname: "Tista",
        profilepic: "https://i.imgur.com/UBYm91l.jpg",
        email: "artista@gmail.com",
        password:
            "$2a$10$kui1uaMdN0Ak2adaLBGkROoiCI6mcRKdbnEkpWFr1/5uBQw4fDRX.",
        birth: 21021999,
        type: "artist",
        state: "approved",
    },
    {
        username: "admin",
        name: "Admin",
        lastname: "Istrador",
        profilepic: "https://i.imgur.com/LBFq1of.png",
        email: "admin@gmail.com",
        password:
            "$2a$10$kui1uaMdN0Ak2adaLBGkROoiCI6mcRKdbnEkpWFr1/5uBQw4fDRX.",
        birth: 21021999,
        type: "admin",
        state: "approved",
        twoFactor: "",
    },
];

module.exports = arrayOfUsers;
